services:
  - type: web
    name: isimbay-dating-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: "8088318424:AAHe8zUKX4nC2SoqcW983UmlT_SLIkOPBUY"
